# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/kuhiu/5e8324a1-752c-4afa-961c-05d693d0ddc6/SmartNavSys/docker-for-petalinux/smartscout-vivado/smartnav-vivado/smartnav-vivado.srcs/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xci
# IP: The module: 'design_1_v_frmbuf_wr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/kuhiu/5e8324a1-752c-4afa-961c-05d693d0ddc6/SmartNavSys/docker-for-petalinux/smartscout-vivado/smartnav-vivado/smartnav-vivado.srcs/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_frmbuf_wr_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/kuhiu/5e8324a1-752c-4afa-961c-05d693d0ddc6/SmartNavSys/docker-for-petalinux/smartscout-vivado/smartnav-vivado/smartnav-vivado.srcs/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xci
# IP: The module: 'design_1_v_frmbuf_wr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/kuhiu/5e8324a1-752c-4afa-961c-05d693d0ddc6/SmartNavSys/docker-for-petalinux/smartscout-vivado/smartnav-vivado/smartnav-vivado.srcs/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_frmbuf_wr_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
