// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStr (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        img_V_val_0_V_din,
        img_V_val_0_V_full_n,
        img_V_val_0_V_write,
        img_V_val_1_V_din,
        img_V_val_1_V_full_n,
        img_V_val_1_V_write,
        img_V_val_2_V_din,
        img_V_val_2_V_full_n,
        img_V_val_2_V_write,
        HwReg_height_cast5_loc_dout,
        HwReg_height_cast5_loc_empty_n,
        HwReg_height_cast5_loc_read,
        HwReg_width_cast6_loc_dout,
        HwReg_width_cast6_loc_empty_n,
        HwReg_width_cast6_loc_read,
        colorFormat,
        HwReg_height_cast5_loc_out_din,
        HwReg_height_cast5_loc_out_full_n,
        HwReg_height_cast5_loc_out_write,
        HwReg_width_cast6_loc_out_din,
        HwReg_width_cast6_loc_out_full_n,
        HwReg_width_cast6_loc_out_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_pp1_stage0 = 9'd32;
parameter    ap_ST_fsm_state8 = 9'd64;
parameter    ap_ST_fsm_state9 = 9'd128;
parameter    ap_ST_fsm_state10 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [7:0] img_V_val_0_V_din;
input   img_V_val_0_V_full_n;
output   img_V_val_0_V_write;
output  [7:0] img_V_val_1_V_din;
input   img_V_val_1_V_full_n;
output   img_V_val_1_V_write;
output  [7:0] img_V_val_2_V_din;
input   img_V_val_2_V_full_n;
output   img_V_val_2_V_write;
input  [9:0] HwReg_height_cast5_loc_dout;
input   HwReg_height_cast5_loc_empty_n;
output   HwReg_height_cast5_loc_read;
input  [10:0] HwReg_width_cast6_loc_dout;
input   HwReg_width_cast6_loc_empty_n;
output   HwReg_width_cast6_loc_read;
input  [7:0] colorFormat;
output  [9:0] HwReg_height_cast5_loc_out_din;
input   HwReg_height_cast5_loc_out_full_n;
output   HwReg_height_cast5_loc_out_write;
output  [10:0] HwReg_width_cast6_loc_out_din;
input   HwReg_width_cast6_loc_out_full_n;
output   HwReg_width_cast6_loc_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg img_V_val_0_V_write;
reg img_V_val_1_V_write;
reg img_V_val_2_V_write;
reg HwReg_height_cast5_loc_read;
reg HwReg_width_cast6_loc_read;
reg HwReg_height_cast5_loc_out_write;
reg HwReg_width_cast6_loc_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [23:0] AXI_video_strm_V_data_V_0_data_out;
wire    AXI_video_strm_V_data_V_0_vld_in;
wire    AXI_video_strm_V_data_V_0_vld_out;
wire    AXI_video_strm_V_data_V_0_ack_in;
reg    AXI_video_strm_V_data_V_0_ack_out;
reg   [23:0] AXI_video_strm_V_data_V_0_payload_A;
reg   [23:0] AXI_video_strm_V_data_V_0_payload_B;
reg    AXI_video_strm_V_data_V_0_sel_rd;
reg    AXI_video_strm_V_data_V_0_sel_wr;
wire    AXI_video_strm_V_data_V_0_sel;
wire    AXI_video_strm_V_data_V_0_load_A;
wire    AXI_video_strm_V_data_V_0_load_B;
reg   [1:0] AXI_video_strm_V_data_V_0_state;
wire    AXI_video_strm_V_data_V_0_state_cmp_full;
reg   [0:0] AXI_video_strm_V_user_V_0_data_out;
wire    AXI_video_strm_V_user_V_0_vld_in;
wire    AXI_video_strm_V_user_V_0_vld_out;
wire    AXI_video_strm_V_user_V_0_ack_in;
reg    AXI_video_strm_V_user_V_0_ack_out;
reg   [0:0] AXI_video_strm_V_user_V_0_payload_A;
reg   [0:0] AXI_video_strm_V_user_V_0_payload_B;
reg    AXI_video_strm_V_user_V_0_sel_rd;
reg    AXI_video_strm_V_user_V_0_sel_wr;
wire    AXI_video_strm_V_user_V_0_sel;
wire    AXI_video_strm_V_user_V_0_load_A;
wire    AXI_video_strm_V_user_V_0_load_B;
reg   [1:0] AXI_video_strm_V_user_V_0_state;
wire    AXI_video_strm_V_user_V_0_state_cmp_full;
reg   [0:0] AXI_video_strm_V_last_V_0_data_out;
wire    AXI_video_strm_V_last_V_0_vld_in;
wire    AXI_video_strm_V_last_V_0_vld_out;
wire    AXI_video_strm_V_last_V_0_ack_in;
reg    AXI_video_strm_V_last_V_0_ack_out;
reg   [0:0] AXI_video_strm_V_last_V_0_payload_A;
reg   [0:0] AXI_video_strm_V_last_V_0_payload_B;
reg    AXI_video_strm_V_last_V_0_sel_rd;
reg    AXI_video_strm_V_last_V_0_sel_wr;
wire    AXI_video_strm_V_last_V_0_sel;
wire    AXI_video_strm_V_last_V_0_load_A;
wire    AXI_video_strm_V_last_V_0_load_B;
reg   [1:0] AXI_video_strm_V_last_V_0_state;
wire    AXI_video_strm_V_last_V_0_state_cmp_full;
wire    AXI_video_strm_V_dest_V_0_vld_in;
reg    AXI_video_strm_V_dest_V_0_ack_out;
reg   [1:0] AXI_video_strm_V_dest_V_0_state;
reg    s_axis_video_TDATA_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage0;
wire   [0:0] icmp_ln185_fu_446_p2;
wire   [0:0] or_ln189_fu_460_p2;
wire    ap_CS_fsm_state9;
wire   [0:0] ap_phi_mux_eol_2_i_i_phi_fu_385_p4;
reg    img_V_val_0_V_blk_n;
reg    ap_enable_reg_pp1_iter1;
reg   [0:0] icmp_ln185_reg_582;
reg    img_V_val_1_V_blk_n;
reg    img_V_val_2_V_blk_n;
reg    HwReg_height_cast5_loc_blk_n;
reg    HwReg_width_cast6_loc_blk_n;
reg    HwReg_height_cast5_loc_out_blk_n;
reg    HwReg_width_cast6_loc_out_blk_n;
reg   [0:0] eol_reg_288;
reg   [23:0] axi_data_V_1_i_i_reg_299;
reg   [0:0] eol_0_i_i_reg_310;
reg   [10:0] j_0_i_i_reg_322;
reg   [0:0] axi_last_V_2_i_i_reg_333;
reg   [23:0] p_Val2_s_reg_346;
reg   [10:0] HwReg_width_cast6_lo_reg_516;
reg    ap_block_state1;
wire   [10:0] zext_ln164_fu_402_p1;
reg   [10:0] zext_ln164_reg_521;
wire    ap_CS_fsm_state2;
wire    grp_reg_unsigned_short_s_fu_406_ap_ready;
wire    grp_reg_unsigned_short_s_fu_406_ap_done;
wire    grp_reg_unsigned_short_s_fu_412_ap_ready;
wire    grp_reg_unsigned_short_s_fu_412_ap_done;
reg    ap_block_state2_on_subcall_done;
wire   [10:0] grp_reg_unsigned_short_s_fu_406_ap_return;
reg   [10:0] tmp_i_i_reg_531;
wire   [10:0] grp_reg_unsigned_short_s_fu_412_ap_return;
reg   [10:0] tmp_i_i_334_reg_536;
reg   [23:0] tmp_data_V_reg_541;
reg   [0:0] tmp_last_V_reg_549;
wire   [9:0] trunc_ln182_fu_422_p1;
reg   [9:0] trunc_ln182_reg_561;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln212_fu_425_p2;
reg   [0:0] icmp_ln212_reg_566;
wire   [0:0] icmp_ln182_fu_435_p2;
wire    ap_CS_fsm_state5;
wire   [9:0] i_fu_440_p2;
reg   [9:0] i_reg_577;
reg    ap_predicate_op74_read_state6;
reg    ap_block_state6_pp1_stage0_iter0;
wire    io_acc_block_signal_op90;
reg    ap_block_state7_pp1_stage0_iter1;
reg    ap_block_pp1_stage0_11001;
wire   [10:0] j_fu_451_p2;
wire   [7:0] tmp_val_2_V_fu_490_p3;
reg   [7:0] tmp_val_2_V_reg_595;
wire   [7:0] tmp_val_1_V_fu_497_p3;
reg   [7:0] tmp_val_1_V_reg_600;
wire   [7:0] tmp_val_0_V_fu_504_p3;
reg   [7:0] tmp_val_0_V_reg_605;
reg    ap_block_state9;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state6;
wire    grp_reg_unsigned_short_s_fu_406_ap_start;
wire    grp_reg_unsigned_short_s_fu_406_ap_idle;
wire    grp_reg_unsigned_short_s_fu_412_ap_start;
wire    grp_reg_unsigned_short_s_fu_412_ap_idle;
reg   [0:0] axi_last_V_0_i_i_reg_257;
reg   [0:0] axi_last_V_3_i_i_reg_358;
wire    ap_CS_fsm_state10;
reg   [23:0] axi_data_V_0_i_i_reg_267;
reg   [23:0] axi_data_V_3_i_i_reg_370;
reg   [9:0] i_0_i_i_reg_277;
reg   [0:0] ap_phi_mux_eol_phi_fu_291_p4;
reg   [23:0] ap_phi_mux_axi_data_V_1_i_i_phi_fu_302_p4;
reg   [0:0] ap_phi_mux_eol_0_i_i_phi_fu_314_p4;
wire   [0:0] ap_phi_reg_pp1_iter0_axi_last_V_2_i_i_reg_333;
reg   [23:0] ap_phi_mux_p_Val2_s_phi_fu_350_p4;
wire   [23:0] ap_phi_reg_pp1_iter0_p_Val2_s_reg_346;
wire    ap_CS_fsm_state8;
reg   [0:0] eol_2_i_i_reg_382;
reg    grp_reg_unsigned_short_s_fu_406_ap_start_reg;
reg    ap_block_state1_ignore_call21;
reg    grp_reg_unsigned_short_s_fu_412_ap_start_reg;
reg    ap_block_state1_ignore_call22;
reg   [0:0] sof_1_i_i_fu_188;
reg    ap_block_pp1_stage0_01001;
wire   [7:0] pix_val_2_V_fu_480_p4;
wire   [7:0] pix_val_0_V_fu_466_p4;
wire   [7:0] pix_val_1_V_36_fu_476_p1;
wire   [0:0] tmp_user_V_fu_418_p1;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_condition_712;
reg    ap_condition_627;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 AXI_video_strm_V_data_V_0_sel_rd = 1'b0;
#0 AXI_video_strm_V_data_V_0_sel_wr = 1'b0;
#0 AXI_video_strm_V_data_V_0_state = 2'd0;
#0 AXI_video_strm_V_user_V_0_sel_rd = 1'b0;
#0 AXI_video_strm_V_user_V_0_sel_wr = 1'b0;
#0 AXI_video_strm_V_user_V_0_state = 2'd0;
#0 AXI_video_strm_V_last_V_0_sel_rd = 1'b0;
#0 AXI_video_strm_V_last_V_0_sel_wr = 1'b0;
#0 AXI_video_strm_V_last_V_0_state = 2'd0;
#0 AXI_video_strm_V_dest_V_0_state = 2'd0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 grp_reg_unsigned_short_s_fu_406_ap_start_reg = 1'b0;
#0 grp_reg_unsigned_short_s_fu_412_ap_start_reg = 1'b0;
end

design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_406(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_406_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_406_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_406_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_406_ap_ready),
    .in_r(zext_ln164_reg_521),
    .ap_return(grp_reg_unsigned_short_s_fu_406_ap_return)
);

design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_412(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_412_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_412_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_412_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_412_ap_ready),
    .in_r(HwReg_width_cast6_lo_reg_516),
    .ap_return(grp_reg_unsigned_short_s_fu_412_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_data_V_0_ack_out) & (1'b1 == AXI_video_strm_V_data_V_0_vld_out))) begin
            AXI_video_strm_V_data_V_0_sel_rd <= ~AXI_video_strm_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_data_V_0_ack_in) & (1'b1 == AXI_video_strm_V_data_V_0_vld_in))) begin
            AXI_video_strm_V_data_V_0_sel_wr <= ~AXI_video_strm_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == AXI_video_strm_V_data_V_0_state) & (1'b0 == AXI_video_strm_V_data_V_0_vld_in)) | ((2'd3 == AXI_video_strm_V_data_V_0_state) & (1'b0 == AXI_video_strm_V_data_V_0_vld_in) & (1'b1 == AXI_video_strm_V_data_V_0_ack_out)))) begin
            AXI_video_strm_V_data_V_0_state <= 2'd2;
        end else if ((((2'd1 == AXI_video_strm_V_data_V_0_state) & (1'b0 == AXI_video_strm_V_data_V_0_ack_out)) | ((2'd3 == AXI_video_strm_V_data_V_0_state) & (1'b0 == AXI_video_strm_V_data_V_0_ack_out) & (1'b1 == AXI_video_strm_V_data_V_0_vld_in)))) begin
            AXI_video_strm_V_data_V_0_state <= 2'd1;
        end else if (((~((1'b0 == AXI_video_strm_V_data_V_0_vld_in) & (1'b1 == AXI_video_strm_V_data_V_0_ack_out)) & ~((1'b0 == AXI_video_strm_V_data_V_0_ack_out) & (1'b1 == AXI_video_strm_V_data_V_0_vld_in)) & (2'd3 == AXI_video_strm_V_data_V_0_state)) | ((2'd1 == AXI_video_strm_V_data_V_0_state) & (1'b1 == AXI_video_strm_V_data_V_0_ack_out)) | ((2'd2 == AXI_video_strm_V_data_V_0_state) & (1'b1 == AXI_video_strm_V_data_V_0_vld_in)))) begin
            AXI_video_strm_V_data_V_0_state <= 2'd3;
        end else begin
            AXI_video_strm_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_dest_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == AXI_video_strm_V_dest_V_0_state) & (1'b0 == AXI_video_strm_V_dest_V_0_vld_in)) | ((2'd3 == AXI_video_strm_V_dest_V_0_state) & (1'b0 == AXI_video_strm_V_dest_V_0_vld_in) & (1'b1 == AXI_video_strm_V_dest_V_0_ack_out)))) begin
            AXI_video_strm_V_dest_V_0_state <= 2'd2;
        end else if ((((2'd1 == AXI_video_strm_V_dest_V_0_state) & (1'b0 == AXI_video_strm_V_dest_V_0_ack_out)) | ((2'd3 == AXI_video_strm_V_dest_V_0_state) & (1'b0 == AXI_video_strm_V_dest_V_0_ack_out) & (1'b1 == AXI_video_strm_V_dest_V_0_vld_in)))) begin
            AXI_video_strm_V_dest_V_0_state <= 2'd1;
        end else if (((~((1'b0 == AXI_video_strm_V_dest_V_0_vld_in) & (1'b1 == AXI_video_strm_V_dest_V_0_ack_out)) & ~((1'b0 == AXI_video_strm_V_dest_V_0_ack_out) & (1'b1 == AXI_video_strm_V_dest_V_0_vld_in)) & (2'd3 == AXI_video_strm_V_dest_V_0_state)) | ((2'd1 == AXI_video_strm_V_dest_V_0_state) & (1'b1 == AXI_video_strm_V_dest_V_0_ack_out)) | ((2'd2 == AXI_video_strm_V_dest_V_0_state) & (1'b1 == AXI_video_strm_V_dest_V_0_vld_in)))) begin
            AXI_video_strm_V_dest_V_0_state <= 2'd3;
        end else begin
            AXI_video_strm_V_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_last_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_last_V_0_ack_out) & (1'b1 == AXI_video_strm_V_last_V_0_vld_out))) begin
            AXI_video_strm_V_last_V_0_sel_rd <= ~AXI_video_strm_V_last_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_last_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_last_V_0_ack_in) & (1'b1 == AXI_video_strm_V_last_V_0_vld_in))) begin
            AXI_video_strm_V_last_V_0_sel_wr <= ~AXI_video_strm_V_last_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == AXI_video_strm_V_last_V_0_state) & (1'b0 == AXI_video_strm_V_last_V_0_vld_in)) | ((2'd3 == AXI_video_strm_V_last_V_0_state) & (1'b0 == AXI_video_strm_V_last_V_0_vld_in) & (1'b1 == AXI_video_strm_V_last_V_0_ack_out)))) begin
            AXI_video_strm_V_last_V_0_state <= 2'd2;
        end else if ((((2'd1 == AXI_video_strm_V_last_V_0_state) & (1'b0 == AXI_video_strm_V_last_V_0_ack_out)) | ((2'd3 == AXI_video_strm_V_last_V_0_state) & (1'b0 == AXI_video_strm_V_last_V_0_ack_out) & (1'b1 == AXI_video_strm_V_last_V_0_vld_in)))) begin
            AXI_video_strm_V_last_V_0_state <= 2'd1;
        end else if (((~((1'b0 == AXI_video_strm_V_last_V_0_vld_in) & (1'b1 == AXI_video_strm_V_last_V_0_ack_out)) & ~((1'b0 == AXI_video_strm_V_last_V_0_ack_out) & (1'b1 == AXI_video_strm_V_last_V_0_vld_in)) & (2'd3 == AXI_video_strm_V_last_V_0_state)) | ((2'd1 == AXI_video_strm_V_last_V_0_state) & (1'b1 == AXI_video_strm_V_last_V_0_ack_out)) | ((2'd2 == AXI_video_strm_V_last_V_0_state) & (1'b1 == AXI_video_strm_V_last_V_0_vld_in)))) begin
            AXI_video_strm_V_last_V_0_state <= 2'd3;
        end else begin
            AXI_video_strm_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_user_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_user_V_0_ack_out) & (1'b1 == AXI_video_strm_V_user_V_0_vld_out))) begin
            AXI_video_strm_V_user_V_0_sel_rd <= ~AXI_video_strm_V_user_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_user_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_user_V_0_ack_in) & (1'b1 == AXI_video_strm_V_user_V_0_vld_in))) begin
            AXI_video_strm_V_user_V_0_sel_wr <= ~AXI_video_strm_V_user_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_user_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == AXI_video_strm_V_user_V_0_state) & (1'b0 == AXI_video_strm_V_user_V_0_vld_in)) | ((2'd3 == AXI_video_strm_V_user_V_0_state) & (1'b0 == AXI_video_strm_V_user_V_0_vld_in) & (1'b1 == AXI_video_strm_V_user_V_0_ack_out)))) begin
            AXI_video_strm_V_user_V_0_state <= 2'd2;
        end else if ((((2'd1 == AXI_video_strm_V_user_V_0_state) & (1'b0 == AXI_video_strm_V_user_V_0_ack_out)) | ((2'd3 == AXI_video_strm_V_user_V_0_state) & (1'b0 == AXI_video_strm_V_user_V_0_ack_out) & (1'b1 == AXI_video_strm_V_user_V_0_vld_in)))) begin
            AXI_video_strm_V_user_V_0_state <= 2'd1;
        end else if (((~((1'b0 == AXI_video_strm_V_user_V_0_vld_in) & (1'b1 == AXI_video_strm_V_user_V_0_ack_out)) & ~((1'b0 == AXI_video_strm_V_user_V_0_ack_out) & (1'b1 == AXI_video_strm_V_user_V_0_vld_in)) & (2'd3 == AXI_video_strm_V_user_V_0_state)) | ((2'd1 == AXI_video_strm_V_user_V_0_state) & (1'b1 == AXI_video_strm_V_user_V_0_ack_out)) | ((2'd2 == AXI_video_strm_V_user_V_0_state) & (1'b1 == AXI_video_strm_V_user_V_0_vld_in)))) begin
            AXI_video_strm_V_user_V_0_state <= 2'd3;
        end else begin
            AXI_video_strm_V_user_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln182_fu_435_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((icmp_ln182_fu_435_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state6))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state6);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((icmp_ln182_fu_435_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reg_unsigned_short_s_fu_406_ap_start_reg <= 1'b0;
    end else begin
        if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_reg_unsigned_short_s_fu_406_ap_start_reg <= 1'b1;
        end else if ((grp_reg_unsigned_short_s_fu_406_ap_ready == 1'b1)) begin
            grp_reg_unsigned_short_s_fu_406_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reg_unsigned_short_s_fu_412_ap_start_reg <= 1'b0;
    end else begin
        if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_reg_unsigned_short_s_fu_412_ap_start_reg <= 1'b1;
        end else if ((grp_reg_unsigned_short_s_fu_412_ap_ready == 1'b1)) begin
            grp_reg_unsigned_short_s_fu_412_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_data_V_0_i_i_reg_267 <= axi_data_V_3_i_i_reg_370;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_data_V_0_i_i_reg_267 <= tmp_data_V_reg_541;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        axi_data_V_1_i_i_reg_299 <= p_Val2_s_reg_346;
    end else if (((icmp_ln182_fu_435_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        axi_data_V_1_i_i_reg_299 <= axi_data_V_0_i_i_reg_267;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        axi_data_V_3_i_i_reg_370 <= axi_data_V_1_i_i_reg_299;
    end else if ((~((eol_2_i_i_reg_382 == 1'd0) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out)) & (eol_2_i_i_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        axi_data_V_3_i_i_reg_370 <= AXI_video_strm_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_last_V_0_i_i_reg_257 <= axi_last_V_3_i_i_reg_358;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_V_0_i_i_reg_257 <= tmp_last_V_reg_549;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_627)) begin
        if (((or_ln189_fu_460_p2 == 1'd1) & (icmp_ln185_fu_446_p2 == 1'd0))) begin
            axi_last_V_2_i_i_reg_333 <= ap_phi_mux_eol_phi_fu_291_p4;
        end else if (((or_ln189_fu_460_p2 == 1'd0) & (icmp_ln185_fu_446_p2 == 1'd0))) begin
            axi_last_V_2_i_i_reg_333 <= AXI_video_strm_V_last_V_0_data_out;
        end else if ((1'b1 == 1'b1)) begin
            axi_last_V_2_i_i_reg_333 <= ap_phi_reg_pp1_iter0_axi_last_V_2_i_i_reg_333;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        axi_last_V_3_i_i_reg_358 <= eol_reg_288;
    end else if ((~((eol_2_i_i_reg_382 == 1'd0) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out)) & (eol_2_i_i_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        axi_last_V_3_i_i_reg_358 <= AXI_video_strm_V_last_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        eol_0_i_i_reg_310 <= axi_last_V_2_i_i_reg_333;
    end else if (((icmp_ln182_fu_435_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        eol_0_i_i_reg_310 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        eol_2_i_i_reg_382 <= eol_0_i_i_reg_310;
    end else if ((~((eol_2_i_i_reg_382 == 1'd0) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out)) & (eol_2_i_i_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        eol_2_i_i_reg_382 <= AXI_video_strm_V_last_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        eol_reg_288 <= axi_last_V_2_i_i_reg_333;
    end else if (((icmp_ln182_fu_435_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        eol_reg_288 <= axi_last_V_0_i_i_reg_257;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i_0_i_i_reg_277 <= i_reg_577;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        i_0_i_i_reg_277 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_fu_446_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        j_0_i_i_reg_322 <= j_fu_451_p2;
    end else if (((icmp_ln182_fu_435_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        j_0_i_i_reg_322 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_627)) begin
        if (((or_ln189_fu_460_p2 == 1'd1) & (icmp_ln185_fu_446_p2 == 1'd0))) begin
            p_Val2_s_reg_346 <= ap_phi_mux_axi_data_V_1_i_i_phi_fu_302_p4;
        end else if (((or_ln189_fu_460_p2 == 1'd0) & (icmp_ln185_fu_446_p2 == 1'd0))) begin
            p_Val2_s_reg_346 <= AXI_video_strm_V_data_V_0_data_out;
        end else if ((1'b1 == 1'b1)) begin
            p_Val2_s_reg_346 <= ap_phi_reg_pp1_iter0_p_Val2_s_reg_346;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_fu_446_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        sof_1_i_i_fu_188 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        sof_1_i_i_fu_188 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_data_V_0_load_A)) begin
        AXI_video_strm_V_data_V_0_payload_A <= s_axis_video_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_data_V_0_load_B)) begin
        AXI_video_strm_V_data_V_0_payload_B <= s_axis_video_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_last_V_0_load_A)) begin
        AXI_video_strm_V_last_V_0_payload_A <= s_axis_video_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_last_V_0_load_B)) begin
        AXI_video_strm_V_last_V_0_payload_B <= s_axis_video_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_user_V_0_load_A)) begin
        AXI_video_strm_V_user_V_0_payload_A <= s_axis_video_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_user_V_0_load_B)) begin
        AXI_video_strm_V_user_V_0_payload_B <= s_axis_video_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_lo_reg_516 <= HwReg_width_cast6_loc_dout;
        zext_ln164_reg_521[9 : 0] <= zext_ln164_fu_402_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_reg_577 <= i_fu_440_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln185_reg_582 <= icmp_ln185_fu_446_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln212_reg_566 <= icmp_ln212_fu_425_p2;
        trunc_ln182_reg_561 <= trunc_ln182_fu_422_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_reg_541 <= AXI_video_strm_V_data_V_0_data_out;
        tmp_last_V_reg_549 <= AXI_video_strm_V_last_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_i_i_334_reg_536 <= grp_reg_unsigned_short_s_fu_412_ap_return;
        tmp_i_i_reg_531 <= grp_reg_unsigned_short_s_fu_406_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_fu_446_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        tmp_val_0_V_reg_605 <= tmp_val_0_V_fu_504_p3;
        tmp_val_1_V_reg_600 <= tmp_val_1_V_fu_497_p3;
        tmp_val_2_V_reg_595 <= tmp_val_2_V_fu_490_p3;
    end
end

always @ (*) begin
    if (((~((eol_2_i_i_reg_382 == 1'd0) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out)) & (eol_2_i_i_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_predicate_op74_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b1 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3)))) begin
        AXI_video_strm_V_data_V_0_ack_out = 1'b1;
    end else begin
        AXI_video_strm_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == AXI_video_strm_V_data_V_0_sel)) begin
        AXI_video_strm_V_data_V_0_data_out = AXI_video_strm_V_data_V_0_payload_B;
    end else begin
        AXI_video_strm_V_data_V_0_data_out = AXI_video_strm_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if (((~((eol_2_i_i_reg_382 == 1'd0) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out)) & (eol_2_i_i_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_predicate_op74_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b1 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3)))) begin
        AXI_video_strm_V_dest_V_0_ack_out = 1'b1;
    end else begin
        AXI_video_strm_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((~((eol_2_i_i_reg_382 == 1'd0) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out)) & (eol_2_i_i_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_predicate_op74_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b1 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3)))) begin
        AXI_video_strm_V_last_V_0_ack_out = 1'b1;
    end else begin
        AXI_video_strm_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == AXI_video_strm_V_last_V_0_sel)) begin
        AXI_video_strm_V_last_V_0_data_out = AXI_video_strm_V_last_V_0_payload_B;
    end else begin
        AXI_video_strm_V_last_V_0_data_out = AXI_video_strm_V_last_V_0_payload_A;
    end
end

always @ (*) begin
    if (((~((eol_2_i_i_reg_382 == 1'd0) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out)) & (eol_2_i_i_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_predicate_op74_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b1 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3)))) begin
        AXI_video_strm_V_user_V_0_ack_out = 1'b1;
    end else begin
        AXI_video_strm_V_user_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == AXI_video_strm_V_user_V_0_sel)) begin
        AXI_video_strm_V_user_V_0_data_out = AXI_video_strm_V_user_V_0_payload_B;
    end else begin
        AXI_video_strm_V_user_V_0_data_out = AXI_video_strm_V_user_V_0_payload_A;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_blk_n = HwReg_height_cast5_loc_empty_n;
    end else begin
        HwReg_height_cast5_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_out_blk_n = HwReg_height_cast5_loc_out_full_n;
    end else begin
        HwReg_height_cast5_loc_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_out_write = 1'b1;
    end else begin
        HwReg_height_cast5_loc_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_read = 1'b1;
    end else begin
        HwReg_height_cast5_loc_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_loc_blk_n = HwReg_width_cast6_loc_empty_n;
    end else begin
        HwReg_width_cast6_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_loc_out_blk_n = HwReg_width_cast6_loc_out_full_n;
    end else begin
        HwReg_width_cast6_loc_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_loc_out_write = 1'b1;
    end else begin
        HwReg_width_cast6_loc_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_loc_read = 1'b1;
    end else begin
        HwReg_width_cast6_loc_read = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln185_fu_446_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln182_fu_435_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_axi_data_V_1_i_i_phi_fu_302_p4 = p_Val2_s_reg_346;
    end else begin
        ap_phi_mux_axi_data_V_1_i_i_phi_fu_302_p4 = axi_data_V_1_i_i_reg_299;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_eol_0_i_i_phi_fu_314_p4 = axi_last_V_2_i_i_reg_333;
    end else begin
        ap_phi_mux_eol_0_i_i_phi_fu_314_p4 = eol_0_i_i_reg_310;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_eol_phi_fu_291_p4 = axi_last_V_2_i_i_reg_333;
    end else begin
        ap_phi_mux_eol_phi_fu_291_p4 = eol_reg_288;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_712)) begin
        if ((or_ln189_fu_460_p2 == 1'd1)) begin
            ap_phi_mux_p_Val2_s_phi_fu_350_p4 = ap_phi_mux_axi_data_V_1_i_i_phi_fu_302_p4;
        end else if ((or_ln189_fu_460_p2 == 1'd0)) begin
            ap_phi_mux_p_Val2_s_phi_fu_350_p4 = AXI_video_strm_V_data_V_0_data_out;
        end else begin
            ap_phi_mux_p_Val2_s_phi_fu_350_p4 = ap_phi_reg_pp1_iter0_p_Val2_s_reg_346;
        end
    end else begin
        ap_phi_mux_p_Val2_s_phi_fu_350_p4 = ap_phi_reg_pp1_iter0_p_Val2_s_reg_346;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_V_val_0_V_blk_n = img_V_val_0_V_full_n;
    end else begin
        img_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_V_val_0_V_write = 1'b1;
    end else begin
        img_V_val_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_V_val_1_V_blk_n = img_V_val_1_V_full_n;
    end else begin
        img_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_V_val_1_V_write = 1'b1;
    end else begin
        img_V_val_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_V_val_2_V_blk_n = img_V_val_2_V_full_n;
    end else begin
        img_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_582 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_V_val_2_V_write = 1'b1;
    end else begin
        img_V_val_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln182_fu_435_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((eol_2_i_i_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9)) | ((or_ln189_fu_460_p2 == 1'd0) & (icmp_ln185_fu_446_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        s_axis_video_TDATA_blk_n = AXI_video_strm_V_data_V_0_state[1'd0];
    end else begin
        s_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_user_V_fu_418_p1 == 1'd0) & (1'b1 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((tmp_user_V_fu_418_p1 == 1'd1) & (1'b1 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln182_fu_435_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((icmp_ln185_fu_446_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((icmp_ln185_fu_446_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if ((~((eol_2_i_i_reg_382 == 1'd0) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out)) & (eol_2_i_i_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if ((~((eol_2_i_i_reg_382 == 1'd0) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out)) & (ap_phi_mux_eol_2_i_i_phi_fu_385_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AXI_video_strm_V_data_V_0_ack_in = AXI_video_strm_V_data_V_0_state[1'd1];

assign AXI_video_strm_V_data_V_0_load_A = (~AXI_video_strm_V_data_V_0_sel_wr & AXI_video_strm_V_data_V_0_state_cmp_full);

assign AXI_video_strm_V_data_V_0_load_B = (AXI_video_strm_V_data_V_0_state_cmp_full & AXI_video_strm_V_data_V_0_sel_wr);

assign AXI_video_strm_V_data_V_0_sel = AXI_video_strm_V_data_V_0_sel_rd;

assign AXI_video_strm_V_data_V_0_state_cmp_full = ((AXI_video_strm_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign AXI_video_strm_V_data_V_0_vld_in = s_axis_video_TVALID;

assign AXI_video_strm_V_data_V_0_vld_out = AXI_video_strm_V_data_V_0_state[1'd0];

assign AXI_video_strm_V_dest_V_0_vld_in = s_axis_video_TVALID;

assign AXI_video_strm_V_last_V_0_ack_in = AXI_video_strm_V_last_V_0_state[1'd1];

assign AXI_video_strm_V_last_V_0_load_A = (~AXI_video_strm_V_last_V_0_sel_wr & AXI_video_strm_V_last_V_0_state_cmp_full);

assign AXI_video_strm_V_last_V_0_load_B = (AXI_video_strm_V_last_V_0_state_cmp_full & AXI_video_strm_V_last_V_0_sel_wr);

assign AXI_video_strm_V_last_V_0_sel = AXI_video_strm_V_last_V_0_sel_rd;

assign AXI_video_strm_V_last_V_0_state_cmp_full = ((AXI_video_strm_V_last_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign AXI_video_strm_V_last_V_0_vld_in = s_axis_video_TVALID;

assign AXI_video_strm_V_last_V_0_vld_out = AXI_video_strm_V_last_V_0_state[1'd0];

assign AXI_video_strm_V_user_V_0_ack_in = AXI_video_strm_V_user_V_0_state[1'd1];

assign AXI_video_strm_V_user_V_0_load_A = (~AXI_video_strm_V_user_V_0_sel_wr & AXI_video_strm_V_user_V_0_state_cmp_full);

assign AXI_video_strm_V_user_V_0_load_B = (AXI_video_strm_V_user_V_0_state_cmp_full & AXI_video_strm_V_user_V_0_sel_wr);

assign AXI_video_strm_V_user_V_0_sel = AXI_video_strm_V_user_V_0_sel_rd;

assign AXI_video_strm_V_user_V_0_state_cmp_full = ((AXI_video_strm_V_user_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign AXI_video_strm_V_user_V_0_vld_in = s_axis_video_TVALID;

assign AXI_video_strm_V_user_V_0_vld_out = AXI_video_strm_V_user_V_0_state[1'd0];

assign HwReg_height_cast5_loc_out_din = HwReg_height_cast5_loc_dout;

assign HwReg_width_cast6_loc_out_din = HwReg_width_cast6_loc_dout;

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((icmp_ln185_reg_582 == 1'd0) & (io_acc_block_signal_op90 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1)) | ((1'b0 == AXI_video_strm_V_data_V_0_vld_out) & (ap_predicate_op74_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((icmp_ln185_reg_582 == 1'd0) & (io_acc_block_signal_op90 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1)) | ((1'b0 == AXI_video_strm_V_data_V_0_vld_out) & (ap_predicate_op74_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((icmp_ln185_reg_582 == 1'd0) & (io_acc_block_signal_op90 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1)) | ((1'b0 == AXI_video_strm_V_data_V_0_vld_out) & (ap_predicate_op74_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call21 = ((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call22 = ((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_reg_unsigned_short_s_fu_412_ap_done == 1'b0) | (grp_reg_unsigned_short_s_fu_406_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp1_stage0_iter0 = ((1'b0 == AXI_video_strm_V_data_V_0_vld_out) & (ap_predicate_op74_read_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state7_pp1_stage0_iter1 = ((icmp_ln185_reg_582 == 1'd0) & (io_acc_block_signal_op90 == 1'b0));
end

always @ (*) begin
    ap_block_state9 = ((eol_2_i_i_reg_382 == 1'd0) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out));
end

always @ (*) begin
    ap_condition_627 = ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

always @ (*) begin
    ap_condition_712 = ((icmp_ln185_fu_446_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_mux_eol_2_i_i_phi_fu_385_p4 = eol_2_i_i_reg_382;

assign ap_phi_reg_pp1_iter0_axi_last_V_2_i_i_reg_333 = 'bx;

assign ap_phi_reg_pp1_iter0_p_Val2_s_reg_346 = 'bx;

always @ (*) begin
    ap_predicate_op74_read_state6 = ((or_ln189_fu_460_p2 == 1'd0) & (icmp_ln185_fu_446_p2 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign grp_reg_unsigned_short_s_fu_406_ap_start = grp_reg_unsigned_short_s_fu_406_ap_start_reg;

assign grp_reg_unsigned_short_s_fu_412_ap_start = grp_reg_unsigned_short_s_fu_412_ap_start_reg;

assign i_fu_440_p2 = (i_0_i_i_reg_277 + 10'd1);

assign icmp_ln182_fu_435_p2 = ((i_0_i_i_reg_277 == trunc_ln182_reg_561) ? 1'b1 : 1'b0);

assign icmp_ln185_fu_446_p2 = ((j_0_i_i_reg_322 == tmp_i_i_334_reg_536) ? 1'b1 : 1'b0);

assign icmp_ln212_fu_425_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign img_V_val_0_V_din = tmp_val_0_V_reg_605;

assign img_V_val_1_V_din = tmp_val_1_V_reg_600;

assign img_V_val_2_V_din = tmp_val_2_V_reg_595;

assign io_acc_block_signal_op90 = (img_V_val_2_V_full_n & img_V_val_1_V_full_n & img_V_val_0_V_full_n);

assign j_fu_451_p2 = (j_0_i_i_reg_322 + 11'd1);

assign or_ln189_fu_460_p2 = (sof_1_i_i_fu_188 | ap_phi_mux_eol_0_i_i_phi_fu_314_p4);

assign pix_val_0_V_fu_466_p4 = {{ap_phi_mux_p_Val2_s_phi_fu_350_p4[23:16]}};

assign pix_val_1_V_36_fu_476_p1 = ap_phi_mux_p_Val2_s_phi_fu_350_p4[7:0];

assign pix_val_2_V_fu_480_p4 = {{ap_phi_mux_p_Val2_s_phi_fu_350_p4[15:8]}};

assign s_axis_video_TREADY = AXI_video_strm_V_dest_V_0_state[1'd1];

assign start_out = real_start;

assign tmp_user_V_fu_418_p1 = AXI_video_strm_V_user_V_0_data_out;

assign tmp_val_0_V_fu_504_p3 = ((icmp_ln212_reg_566[0:0] === 1'b1) ? pix_val_0_V_fu_466_p4 : pix_val_1_V_36_fu_476_p1);

assign tmp_val_1_V_fu_497_p3 = ((icmp_ln212_reg_566[0:0] === 1'b1) ? pix_val_1_V_36_fu_476_p1 : pix_val_2_V_fu_480_p4);

assign tmp_val_2_V_fu_490_p3 = ((icmp_ln212_reg_566[0:0] === 1'b1) ? pix_val_2_V_fu_480_p4 : pix_val_0_V_fu_466_p4);

assign trunc_ln182_fu_422_p1 = tmp_i_i_reg_531[9:0];

assign zext_ln164_fu_402_p1 = HwReg_height_cast5_loc_dout;

always @ (posedge ap_clk) begin
    zext_ln164_reg_521[10] <= 1'b0;
end

endmodule //design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStr
